<a href="https://colab.research.google.com/github/KATTA-00/CO542-Neural-Networks-Labs/blob/main/lab03/E19129_lab03.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# CO542 - Neural Networks and Fuzzy Systems
## E/19/129 - K.H. Gunawardana

### Lab 03: Generalized Hebbian Learning (GHL)

#### Task 01: GHL for 2D Synthetic Data

In [2]:
import torch

In [3]:
# Generate 1000 samples from 2D Gaussian (mean=0, std=1)
torch.manual_seed(0)
X = torch.randn(1000, 2)

In [4]:
X

tensor([[-1.1258, -1.1524],
        [-0.2506, -0.4339],
        [ 0.8487,  0.6920],
        ...,
        [ 1.6728, -0.3151],
        [-0.2965, -0.3568],
        [ 0.0829, -0.5187]])

In [5]:
# Center the data (subtract mean)
X = X - X.mean(dim=0)

In [6]:
X

tensor([[-1.1174, -1.1910],
        [-0.2421, -0.4726],
        [ 0.8572,  0.6533],
        ...,
        [ 1.6813, -0.3538],
        [-0.2881, -0.3955],
        [ 0.0914, -0.5574]])

In [7]:
# Parameters
epochs = 100
learning_rate = 0.01
n_samples, n_features = X.shape
n_components = 2

# Initialize weights (random)
W = torch.randn(n_components, n_features)

# Normalize rows of W
W = torch.nn.functional.normalize(W, dim=1)

# GHL training loop
for epoch in range(epochs):
    for x in X:
        x = x.view(-1, 1)  # column vector
        y = W @ x          # projections

        # Update each weight vector using Sanger's rule
        for i in range(n_components):
            correction = y[i] * (x.T - y[:i+1].T @ W[:i+1])
            W[i] += learning_rate * correction.squeeze()

    # Optionally: Re-orthonormalize weights every epoch
    W = torch.nn.functional.normalize(W, dim=1)

In [8]:
print("Final GHL Weights (each row is a component):")
print(W)

Final GHL Weights (each row is a component):
tensor([[ 0.1193,  0.9929],
        [-0.9990,  0.0444]])


In [7]:
# Use PyTorch SVD to compute PCA components
U, S, Vt = torch.linalg.svd(X.T)
print("PCA Components (rows):")
print(Vt[:2])  # top 2 principal components

PCA Components (rows):
tensor([[-0.0409, -0.0153,  0.0235,  ..., -0.0029, -0.0132, -0.0163],
        [-0.0292, -0.0053,  0.0236,  ...,  0.0542, -0.0071,  0.0055]])
